jar_of_green_browser_id_login:
    pattern:  /login/
    defaults: { _controller: JarOfGreenBrowserIDBundle:Default:login }

jar_of_green_browser_id_logout:
    pattern:  /logout/
    defaults: { _controller: JarOfGreenBrowserIDBundle:Default:logout }
    
    
