jar_of_green_sample_app:
    resource: "@JarOfGreenSampleAppBundle/Resources/config/routing.yml"
    prefix:   /

jar_of_green_browser_id:
    resource: "@JarOfGreenBrowserIDBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
